site_name: Math pour le lycée
site_url: https://cedric-todaro.github.io/m

nav:
  - Accueil: index.md
  # - 2nde:
  #     - Ensembles de nombres: 2nde/Ensembles-de-nombres.md
  # - Divers: divers.md

theme:
  name: mkdocs
  color_mode: auto
  user_color_mode_toggle: true
  nav_style: primary
  locale: fr
  navigation_depth: 4
  highlightjs: true
  hljs_languages:
    - python

extra_css:
  - extra.css

extra_javascript:
  - mathjax.js

markdown_extensions:
  - smarty
  - sane_lists
  - admonition
  - legacy_attrs
  - pymdownx.caret
  - pymdownx.extra
  - pymdownx.blocks.details
  - pymdownx.blocks.caption
  - pymdownx.tasklist
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_alt
