site_name: Math pour le lycée
site_url: https://cedric-todaro.github.io/m

nav:
  - Accueil: index.md
  - Divers: divers.md

theme:
  name: mkdocs
  color_mode: auto
  user_color_mode_toggle: true
  nav_style: primary
  locale: fr
  navigation_depth: 4
  highlightjs: true
  hljs_languages:
    - python

extra_css:
  - extra.css
  - https://cdn.jsdelivr.net/gh/rod2ik/cdn@main/mkdocs/css/massilia-mermaid.css

extra_javascript:
  - mathjax.js
  - https://cdnjs.cloudflare.com/ajax/libs/mermaid/8.13.8/mermaid.min.js
  - https://cdn.jsdelivr.net/gh/rod2ik/cdn@main/mkdocs/javascripts/massilia-mermaid.js

markdown_extensions:
  - smarty
  - sane_lists
  - admonition
  - legacy_attrs
  - pymdownx.caret
  - pymdownx.extra
  - pymdownx.blocks.details
  - pymdownx.blocks.caption
  - pymdownx.tasklist
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_alt
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format


