site_name: Math pour le lycée
site_url: https://cedric-todaro.github.io/m

nav:
  - Accueil: index.md
  - 2nde:
      - 2nde/Arithmetique.md
      - 2nde/Calcul-algebrique.md
      - 2nde/Droites-du-plan.md
      - 2nde/Droites-et-systemes.md
      - 2nde/Ensembles-de-nombres.md
      - 2nde/Fonctions-affines.md
      - 2nde/Probabilite-echantillonnage.md
      - 2nde/Probabilite.md
  - Divers:
      - Help: divers.md
      - Testouille: test.md

theme:
  name: readthedocs
  locale: fr
  highlightjs: true
  hljs_languages:
    - python

extra_css:
  - extra.css
  - https://cdn.jsdelivr.net/gh/rod2ik/cdn@main/mkdocs/css/massilia-mermaid.css

extra_javascript:
  - mathjax.js
  - https://cdnjs.cloudflare.com/ajax/libs/mermaid/8.13.8/mermaid.min.js
  - https://cdn.jsdelivr.net/gh/rod2ik/cdn@main/mkdocs/javascripts/massilia-mermaid.js

markdown_extensions:
  - smarty
  - sane_lists
  - admonition
  - legacy_attrs
  - pymdownx.caret
  - pymdownx.extra
  - pymdownx.blocks.details
  - pymdownx.blocks.caption
  - pymdownx.tasklist
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_alt
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format
